### ISSUE TITLE
Add space button not functioning

### ISSUE THREAD

**Issue by ciserman** [riserperson/bingo#1]
Steps to Reproduce:
1. Click 'Create New Game'
2. Add text to the 'New Space' field
3. Click 'Add Space'

Expected Result:
- A new space is added
Actual Result:
- Nothing happens

![image](https://user-images.githubusercontent.com/17324163/150407334-67ae9658-a410-4955-9641-11f0af798269.png)

**Comment by riserperson** [comment]
dumb capitalization typo in spaceController.js. Fixed!

**Comment by riserperson** [comment]
Commit ba876ea6c284ceb39f6df87d7b4c56c550ce32d8 fixes this issue on line 21 of spaceController.js
