### ISSUE TITLE
Put some goddamn styling on this thing

### ISSUE THREAD

**Issue by riserperson** [riserperson/bingo#5]

**Comment by j-me3000** [comment]
So I finally found some time and motivation to look over the project and start storyboarding some design concepts.

I will focus on the end-user ui first, as that effects the actual gameplay. The host ui will follow.

I started poking around and will be jumping off with the basic card structure [found here](https://codepen.io/j-me3000/pen/LYOYamM).

One of my concerns is that the user will not be able to turn off their device and rejoin, say the next day. My initial idea was to hadle this via a playerid that is saved in a cookie. However, this would cause the interface to have to connect to the db each time the device is turned on. 
In the example above, the field text is inserted via js, so this data can be saved in the cookie itself, bypassing the need for constant db requests.

**Comment by j-me3000** [comment]
ok, ditching the previously mentioned html and css structure and rebuilding from scratch. Keeping the js to call tile info.

Challenges & Goals (Main Game Card UI):
- Responsiveness: Almost all players will be on mobile devices. The game should be playable on 375px wide screen (pre 2014 device combatibility).
   - - > Grid structure with game card min-width: 375px 
- The text will be VERY limited on each card, if readable in 5 x 5 grid structute ( ca. 70 x 70 px for each tile!)
   - - > Display only tile number on front side, flip to back of tile on :focus. Tile back transforms to fill card width (iE screen width)

**Comment by riserperson** [comment]
Hey good points on responsiveness and styling for small screens. Regarding persistence, that's also an important thing that @ciserman and I had chatted about earlier this week. I wanted to avoid the need for any kind of login or cookie to keep things simple. The alternative I opted for in the gameflow is that people get some kind of a notification (email or SMS) with a persistent code that's tied to the bingo card record in the DB. So if they need to go back to it later, they just click that link again. 

You probably already figured this out, but all the layout for the views is in the "views" directory here, and its using Pug (https://pugjs.org/api/getting-started.html). Custom styling is in the public/stylesheets/style.css file. Bootstrap is currently being loaded by the page but not written into the page elements yet.

**Comment by riserperson** [comment]
If you want to build something in HTML I can translate it into Pug.

**Comment by riserperson** [comment]
I like your idea for using numbers to identify the spaces that get expanded and "flipped" to reveal their contents on small screens.

**Comment by riserperson** [comment]
I'm going to close this for now since we at least have some styling. open to further refinements but at least it works for now.
